add theme
gradussus/petly-front pull request #18
Opened 2023-03-19 19:52 UTC by maksnovakov

2023-03-19 21:41 UTC, gradussus requested changes

2023-03-19 21:41 UTC, gradussus commented on src/theme.js
> +    tablet: '(min-width: 768px,max-width 1279px)',
Тут ніби ж треба : '(min-width: 768px) and(max-width 1279px)',

2023-03-20 08:07 UTC, maksnovakov commented on src/theme.js
> +    tablet: '(min-width: 768px,max-width 1279px)',
не правильно записав,чи що? нне зрозумів, ще не прокунився)

2023-03-20 08:42 UTC, IvanBlazhko approved these changes

2023-03-20 08:44 UTC, closed without merging