Feature/home
gradussus/petly-front pull request #19
Opened 2023-03-19 19:52 UTC by AlexCheverda

Додано елементи сторінки Home без стилізації

2023-03-19 21:54 UTC, gradussus requested changes
Треба притримуватись стандарту форматування. Використовуй лише прітієр з налаштуваннями із прітієр.джсон що вже є в проєкті

2023-03-20 06:41 UTC, AlexCheverda commented
Прибрав конфлікт в Header.jsx

2023-03-20 08:01 UTC, gradussus requested changes
Привіт. Треба притримуватися одного стилю. У нас за редагування коли відповідає прітієр із однаковими налаштування у в усіх. Прибери зайве, бо 23 змінених файли це пекло. І так буде в будь-якому твоеиу реквесті, так як в усіх інших інші налаштування
Імеджи також треба десь оркемо винести

2023-03-20 08:11 UTC, AlexCheverda commented
OK

2023-03-20 11:14 UTC, AlexCheverda commented
Привіт. Файл Prettierrc у мене точно такий же, я перевірив. Імейджи перенесу, коли налаштую стилі.

2023-03-20 11:18 UTC, gradussus requested changes
"devDependencies": {
    "husky": "^4.3.8",
    "lint-staged": "^13.2.0",
    "prettier": "^2.8.4"

Ми використовуємо лише прітієр. І то, його можна не ставити в проєкт, якщо він встановлений локально

2023-03-20 11:21 UTC, AlexCheverda commented
Видалити тільки "prettier": "^2.8.4", чи все із "devDependencies"? Не зрозумів

2023-03-20 15:06 UTC, AlexCheverda commented
конфликты устранены

2023-03-20 18:41 UTC, closed without merging