initial commit for OurFriendsPage
gradussus/petly-front pull request #22
Opened 2023-03-19 23:58 UTC by MykolaPom

додав відтестовану сторіну друзів без фінальних стилів

2023-03-20 07:56 UTC, gradussus requested changes
Привіт
Переглянь яка структура у інших і зроби так само, бо це не правильно коди усі компоненти написано однаково, а один геть по іншому
1. Стилі в окремий файл
2. Styled components
3. Фетч через аксіом
Також не дуже бажано чакра, але вже нехай поки залишається

2023-03-20 08:01 UTC, MykolaPom commented
Привіт
Так, стилі зроблю по загальному принципу, це поки тимчасовий варіант. 
В решті теж зміню

2023-03-20 08:06 UTC, gradussus commented
І ще, одразу не написав. В нас є файл теми, там усі основні стилі прописано (шрифт, кольора і тд), користуйся ним

2023-03-20 08:16 UTC, MykolaPom commented
так, все зроблю

2023-03-21 07:50 UTC, gradussus approved these changes

2023-03-21 07:57 UTC, merged